name: embrocation
favicon: null
layout_spectrum: 0.170325618237257
typography_spectrum: 0.24761225236579776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5221462140325457
  lightness: 0.14244313957169652
  saturation: 0.9662546326871961
  rhythmicContrast: 0.28134464961476624
purpose: []
